<?php echo form_open('cart/update'); ?>

<table cellpadding="6" cellspacing="0" style="width:100%" border="0" class="table table-bordered">

    <tr id="linha-cart">
        <th>Qtde</th>
        <th>Filme</th>
        <th style="text-align:right">Preço</th>
        <th style="text-align:right">Sub-Total</th>
        <th style="text-align:center">Delete</th>
    </tr>

    <?php $i = 1; ?>

    <?php foreach ($this->cart->contents() as $items): ?>

        <?php echo form_hidden($i . '[rowid]', $items['rowid']); ?>

        <tr>
            <td><?php echo form_input(array('name' => $i . '[qty]', 'value' => $items['qty'], 'maxlength' => '3', 'size' => '5', 'class' => 'input input-mini')); ?></td>
            <td>
                <?php echo $items['name']; ?>

                <?php if ($this->cart->has_options($items['rowid']) == TRUE): ?>

                    <p>
                        <?php foreach ($this->cart->product_options($items['rowid']) as $option_name => $option_value): ?>

                            <strong><?php echo $option_name; ?>:</strong> <?php echo $option_value; ?><br />

                        <?php endforeach; ?>
                    </p>

                <?php endif; ?>

            </td>
            <td style="text-align:right"><?php echo $this->cart->format_number($items['price']); ?></td>
            <td style="text-align:right">$<?php echo $this->cart->format_number($items['subtotal']); ?></td>
            <td style="text-align:center"><?php echo anchor('cart/delete/'.$items['rowid'], img('public/img/delete.png')); ?></td>
        </tr>

        <?php $i++; ?>

    <?php endforeach; ?>

    <tr>
        <td colspan="3"> </td>
        <td class="right"><strong>Total</strong></td>
        <td class="right">$<?php echo $this->cart->format_number($this->cart->total()); ?></td>
    </tr>

</table>

<p><?php echo form_submit(array('name' => '', 'class' => 'btn btn-primary', 'value' => 'Atualizar Carrinho')); ?> <?php echo anchor('cart/limpar', 'Limpar Carrinho', array('class' => 'btn btn-primary'))  ?></p>